{{- define "common.istio_base" -}}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: microservices-on-gw
spec:
  selector:
    istio: ingressgateway #será manipulado pelo ingress padrao do istio
  servers:
  - hosts:
    - microservices.me
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: microservices-on-certificate # nome do certificado utilizado
      mode: SIMPLE #semantica normal será aplicada.
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: microservices-on-vs
spec:
  gateways:
  - microservices-on-gw
  hosts:
  - microservices.me #especifica encaminhara solicitacoes para este host, atraves do gateway microservices-on-gw
  http:
  - match:
      - uri:
          prefix: /api/v1/transactions
    route:
      - destination:
          host: transacao-service
          port:
            number: 80
---
apiVersion: networking.istio.io/v1beta1 #pendente colocar health de outros services
kind: Gateway
metadata:
  name: health-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "health.microservices.me"
      port:
        number: 443
        name: https-health
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: microservices-on-certificate
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: health-vs
spec:
  hosts:
    - "health.microservices.me"
  gateways:
    - health-gateway
  http:
    - route:
        - destination:
            host: conta
            port:
              number: 4004
{{- end -}}
