version: "3.3"
services:

  transacao:
    image: fabricio211/transacao-service
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=test

  fraud:
    image: fabricio211/fraude-service
    ports:
      - 8082:8082

  payment:
    image: fabricio211/payment-service
    ports:
      - 8083:8083